<?php

namespace App\Entities;

class Banco extends FirebirdModel
{

	protected $fillable = ['AUXBANCOS', 'LIMITE', 'CODUSUALT', 'CODUSUCRIA', 'DATAALT', 'DATACRIA', 'DIGITOCC', 'DIGITOAG', 'CARTEIRA', 'NUMEROBANCO', 'BANCO', 'NOMECEDENTE', 'AG', 'CC', 'NOSSONUMERO', 'SEQUENCIACNAB', 'NOMEARQUIVOCNAB', 'LAYOUTCNAB', 'CODIGOCEDENTE', 'TIPOIMPRESSAOCNAB', 'DIRETORIOCNAB', 'ARQUIVOLICENCACOBREBEMX', 'CADINATIVO', 'JUROS', 'CODPORTADOR'];

	protected $table = 'BANCOS';

	protected $primaryKey = 'CODBAN';

}
