<?php

namespace App\Entities;

class Cfoptiposai extends FirebirdModel
{

	protected $fillable = ['AUXCFOPTIPOSAI', 'CODCFOPTIPOSAI', 'CODTIPOSAI', 'CODCFOPESTADO', 'CODCFOPFORA', 'CODSITTRIB', 'CODCSTESTADO', 'CODCSTFORA', 'CODCSOSNESTADO', 'CODCSOSNFORA', 'CODCSTIPI', 'CODCSTPIS', 'CODCSTCOFINS', 'ALIQPIS', 'ALIQCOFINS', 'CODLOJA', 'PCTDIFERIMENTO'];

	protected $table = 'CFOPTIPOSAI';

}
