<?php

namespace App\Entities;

class Chamado extends FirebirdModel
{

	protected $fillable = ['DATACRIA', 'CODRESP', 'CODCLI', 'CODTIPOSOLI', 'DESCRICAO', 'SOLUCAO', 'PRAZO', 'DTFINALIZADO', 'OS', 'CODUSUCLI', 'NOMEUSUCLI', 'EMAILUSUCLI', 'ISPENDCLI', 'DTPENDCLI', 'VALORSERV', 'TEMPOSERV', 'CODSTATUSFINAN', 'CODSTATUSHOMO', 'CODSTATUSAUTORI', 'CODUSUCRIA', 'CODUSUALT', 'ISIMPORTADO', 'ISREABERTO', 'ISVISTOFINALIZADO', 'ISPARADO', 'CODTELA', 'PRIORIDADE', 'CODCHAMADOORIGEM', 'PAGDIRETO', 'CODOS', 'PAGQTDE', 'PAGDIA'];

	protected $table = 'CHAMADOS';

	protected $primaryKey = 'CODCHAMADO';

}
