<?php

namespace App\Entities;

class Cliente extends FirebirdModel
{

	protected $fillable = ['AUXCLIENTES', 'OBS', 'OBSVND', 'DATACAD', 'LIMITECREDPRAZO', 'FSALARIO', 'SENHA', 'CODTRA', 'CODVND', 'CODUSUALT', 'CODUSUCRIA',
	'DATAALT', 'DATACRIA', 'UF', 'UF_ENT', 'FAG', 'CIDADE', 'BAIRRO', 'MALADIR',
	'FANTASIA', 'CIDADECOB', 'COMPL_ENT', 'BAIRROCOB', 'CIDADE_ENT',
	'BAIRRO_ENT', 'COMPLEMENTO', 'FMAE', 'FPAI', 'FCARGO', 'FREFFONE',
	'FFONEEMP', 'EMAIL', 'CPCN', 'FATOR', 'COMISSAOVND', 'LIMITECRED', 'DOCS',
	'DATAANI', 'RGDATAEMI', 'SITE', 'EZINE', 'COMRESTRICAO', 'PORTE', 'NUMCLI',
	'NUMFUNC', 'CODLOJA', 'RETEMISS', 'CODFORMA', 'CODSEGMENTO', 'NUMUNIDADES',
	'CODCLISTATUS', 'FCCDIG', 'SEXO', 'REVCOM', 'FISJUR', 'IPIISENTO',
	'MKTSENDSMS', 'ISORGPUBLICO', 'MKTSENDEMAIL', 'ISLOJAVIRTUAL',
	'MKTSENDEMAILCANCBYUSER', 'DDD', 'UFCOB', 'CELULAR', 'CEP', 'CEPCOB',
	'CEP_ENT', 'FCC', 'FBANCO', 'TRABDESDE', 'RGORGEMI', 'RAZAO', 'FREFNOME',
	'FEMPRESA', 'END_ENT', 'ENDERECO', 'CEI', 'CLASSIFICA', 'FAX', 'RGIE',
	'FONE2', 'CONTATO2', 'FONE1', 'CONTATO1', 'DIGITAL', 'ENDCOB', 'IPI',
	'NFPARAMATRIZ', 'DESCVENDA', 'IMUNICIPAL', 'RESTRITO', 'CODPRODTABELA',
	'CODREGIAO', 'CADINATIVO', 'SACUF', 'SACCPCN', 'SACNOME',
	'SACCOMPLEMENTONOME', 'SACRGIE', 'SACENDERECO', 'SACCEP', 'SACBAIRRO',
	'SACCIDADE', 'ISALTERADO', 'TIMEFUTEBOL', 'NSUFRAMA', 'ISSUFRAMA',
	'CODEANCLI', 'NUMERONF', 'ENDERECONF', 'CODCIDNFE', 'EMAILNFE', 'IEISENTO',
	'TPFRETE', 'CODTIPOPAG', 'CODIMPORT', 'TELEFONENF', 'ENDERECOTIPO',
	'ENDERECOCOMPL', 'ISSIMPLESNACIONAL', 'EXPORTASPED', 'INSCRICAOMUNICIPAL',
	'FISICOCOMIE', 'CODNFOPERACAO', 'IDESTRANGEIRO', 'CODNFIEDEST',
	'ISBLOQUEIASISTEMA', 'ISNAOVERBLOQUEIO', 'ISBLOQUEIAALERTAS', 'TIPODESCONTO'];

	protected $table = 'CLIENTES';

	protected $primaryKey = 'CODCLI';

	public $selectable = ['CODCLI', 'RAZAO', 'CIDADE', 'UF'];
}
