<?php

namespace App\Entities;

class Configcli extends FirebirdModel
{

	protected $fillable = ['AUXCONFIGCLI', 'COPIAENDENT', 'NAOCRIACODAUT', 'AVISADUPLBYCEP', 'OBRIGUF', 'OBRIGEND', 'OBRIGCEI', 'OBRIGCEP', 'OBRIGCPCN', 'OBRIGRGIE', 'OBRIGVEND', 'OBRIGFONE', 'OBRIGSEXO', 'OBRIGEMAIL', 'OBRIGSTATUS', 'OBRIGCIDADE', 'OBRIGBAIRRO', 'OBRIGDTNASC', 'OBRIGCONTATO', 'LKRAZAOFANTASIA', 'OBRIGCLASSIFICA', 'VENDEDORNAOVECLI'];

	protected $table = 'CONFIGCLI';

}
