<?php

namespace App\Entities;

use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Configinterno extends FirebirdModel implements Transformable
{
	use TransformableTrait;

	protected $fillable = ['AUXCONFIGINTERNO', 'BI', 'ALMOX', 'PRODUCAO', 'SPCPORTA', 'FTPREMOTOPORTA', 'CRM', 'VDM', 'MUDASENHABD', 'QTDERECRHODA', 'SPCCODSERV', 'IBREMOTOCHARSET', 'SPCSENHA', 'LVFOTOSDIR', 'SPCHOST', 'LVFOTOSHOST', 'IBREMOTOLOGIN', 'FTPREMOTOLOGIN', 'SQLREMOTOBD', 'LVFOTOSPASSWORD', 'LVFOTOSUSERNAME', 'SQLREMOTOUSERNAME', 'SQLREMOTOPASSWORD', 'IBREMOTOHOST', 'FTPREMOTOHOST', 'SMTPREMOTOHOST', 'SMTPREMOTOLOGIN', 'IBREMOTOPASSWORD', 'FTPREMOTOPASSWORD', 'SMTPREMOTOPASSWORD', 'SMTPREMOTOREMETENTE', 'RESPMAILURL', 'MKTURLCANCMAIL', 'IBREMOTOCAMINHO', 'FTPREMOTOCAMINHO', 'SMTPREMOTOASSUNTO', 'LCS', 'MODULONFP', 'MODULOMAPS', 'MODULODEVOLUCAO', 'MODULOEPROCUREMENT', 'DESECUPOM', 'IGSERVECF', 'PIPELINE', 'WORKFLOW', 'CANCEXPEDSTATUS', 'NFEPRODJEW', 'VERSAOHELPDESK', 'HABATIVIDADES', 'HABAJUSTACOMISSAO', 'HABAJUSTACOTACAO', 'HABASSOCIARGRUPOS', 'HABVERIFKARDEX', 'HABRECALQTDEPEDCOMPRA', 'HABRELCONF', 'HABFINPAGPENDCLI', 'HABFINRENCBANC', 'HABFINBORDERO', 'HABFINENVEMAILDADOSFAT', 'HABEXPEDICAO', 'HABOSCONTROLETEMPO', 'HABOSEFETIVORCAMENTO', 'HABESTOQUELOTES', 'HABOSVERESTOQUEDET', 'HABLOTEPHARMALENS', 'HABOSENDENTWEB', 'HABOSLUCRATIVIDADE', 'HABOSBASETROCA', 'HABOSFINANCIAMENTO', 'HABOSREGCOLETAS', 'HABTRANSFERENCIA', 'HABNOTAFISCAL', 'HABVERFOTO', 'HABCADPRODINTERNET', 'HABCADPRODCOMISSAO', 'HABCADPRODFORNECEDOR', 'HABCADPRODCODIGOSEQUIV', 'HABCADSERVCOMISSAO', 'HABCADVENDCOMIPORGRUPO', 'HABCADCLICONTATOS', 'HABCADCLICOMERCIAL', 'HABCADCLIPIPELINE', 'HABCADPRODCALCMARGEM', 'HABAUTOCENTER', 'HABOSIMPORTAR', 'HABENTRADAAGRUPAR', 'HABPEDCOMPDESMEMBRAR', 'HABPRODAUXCOMPRAS', 'HABCNAB', 'HABCADPRAZOSPAGFINANCEIRA', 'HABPREDCOMPDESMEMBRAR', 'HABCADPRAZOSPAGFINANCEIRO', 'HABPEDIDOCOMPRA', 'HABCADSTATUSITEM', 'HABCADREGIOES', 'HABNFREGRADINEXP', 'HABNFREGRADINOS', 'HABGIL', 'HABPARCELASLOG', 'HABPAGRECORRENTE', 'HABVENDARECORRENTE', 'NAOVALIDNFLANC', 'BS', 'DTULTBLQ', 'ISNVB', 'ISREGRANFESPECIFICA', 'HDVERBD', 'BA', 'HELPDESKDIASOUVIDORIA', 'HABCOBRANCA', 'ULTIMALEITURAREMOTA', 'REMOTOISMANUTENCAO', 'REMOTOISBLOQUEADO', 'REMOTOISGERARBOLETO', 'ISFIRE20', 'HABMDFE', 'HABOSEXPORTACAO', 'ISCLOUD'];

	protected $table = 'CONFIGINTERNO';

}
