<?php

namespace App\Entities;

class Configfechacx extends FirebirdModel
{

	protected $fillable = ['AUXCONFIGFECHACX', 'IMPFATGRU', 'FECHAONCE', 'IMPPARDET', 'TRZSOVENDA', 'VALIDADATAS', 'IMPORCFECHA', 'NAOIMPOSCANC', 'IMPMOVSAIRES', 'SEPARAREABERTA', 'NAOIMPOSSEMFIN', 'NAOIMPOSABERTA', 'OSFINANIDENTICO', 'VALIDAVALORSOMENOR', 'NAOVALIDAREABERTAS', 'CODUSUMANDAMAIL', 'VALOROUVALORPG'];

	protected $table = 'CONFIGFECHACX';

}
