<?php

namespace App\Entities;

use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Configpro extends FirebirdModel implements Transformable
{
	use TransformableTrait;

	protected $fillable = ['AUXCONFIGPRO', 'GERACODAUXAUT', 'CADGRUPODESAB', 'CADMARCADESAB', 'USARFORMACAOMARK', 'CONSAPLICQUEBRAR', 'CADPRODDESABPARCIAL', 'FORMMARKUPACUMULATIVO', 'MAXDIASSEMATUVALORES', 'QTDMESESANALISEVNDMED', 'PREMARK1NOME', 'PREMARK2NOME', 'PREMARK3NOME', 'PREMARK4NOME', 'PREMARK5NOME', 'POSMARK1NOME', 'POSMARK2NOME', 'PCTMARK1NOME', 'PCTMARK2NOME', 'PCTMARK3NOME', 'PCTMARK4NOME', 'POSMARK1', 'POSMARK2', 'PCTMARK1', 'PCTMARK2', 'PCTMARK3', 'PCTMARK4', 'ESTOQPCTSEGURANCA', 'ACEITACODPROREPEDITO', 'NAOALTCODIGO', 'MOSTRABTSALVAENOVO', 'CODEAN'];

	protected $table = 'CONFIGPRO';

}
