<?php

namespace App\Entities;

class Conta extends FirebirdModel
{

	protected $fillable = ['AUXCONTAS', 'CODCTR', 'DATAALT', 'DATACRIA', 'CODUSUALT', 'CODUSUCRIA', 'PAGREC', 'INTERNO', 'FLCOMISSAO', 'FLTRANSFIN', 'FLCUSTOSERV', 'FLMERCADORIA', 'CODCONTABIL', 'CONTA', 'CADINATIVO', 'CODGRUCON', 'CODVND', 'LIMITETOTAL', 'ISCOMISSAO', 'ISIMPOSTO', 'ISCOMPRA', 'ISVARIAVEL', 'ISAMORTIZACAO', 'ISFINANCEIRO', 'ISEMPRESTIMO', 'ISIMOBILIZADO', 'ISNAODRE'];

	protected $table = 'CONTAS';

	protected $primaryKey = 'CODCON';

}
