<?php

namespace App\Entities;

class Entcotacoesiten extends FirebirdModel
{

	protected $fillable = ['AUXENTCOTACOESITENS', 'NUMITEM', 'OBS', 'CODPRO', 'CREDITAICMS', 'IPI', 'ICMS', 'QTDE', 'UNITARIO', 'PRECOCOMIMPOSTOS', 'GARI', 'VLRICMS', 'ALIQSUBST', 'PRECOTABELA', 'DESCPRECTAB', 'VLRICMSSUBST', 'RATFRTSEGDESPICMS', 'ISAPROVADO', 'SEGURO', 'FRETEVLR', 'OUTRASDESPESAS', 'UNITARIOSEMIPI', 'TOTALPRD', 'TOTALPRDCOMIMPOSTOS', 'PRECOTABELACOMDESC', 'ALIQINTICMSLOJA'];

	protected $table = 'ENTCOTACOESITENS';

	protected $primaryKey = 'CODENTCOT';

}
