<?php

namespace App\Entities;

class Estoque extends FirebirdModel
{

	protected $fillable = ['AUXESTOQUE', 'MEDIAVNDMESDTATU', 'QTDEMAX', 'MEDIAVNDMES', 'PONTOPEDIDO', 'INTDIASCOMPRA', 'LOTEECONOMICO', 'MEDDIASENTREGA', 'ESTOQPCTSEGURANCA', 'QTDEMIN', 'QTDEESTOQUE', 'CODESTAUXDBX', 'QTDEEXPEDICAO', 'QTDEFISICO'];

	protected $table = 'ESTOQUE';

}
