<?php

namespace App\Entities;

class Expedicaoiten extends FirebirdModel
{

	protected $fillable = ['AUXEXPEDICAOITENS', 'CODOS', 'CODPRO', 'NUMITEM', 'NUMITEMOS', 'ORDEM', 'QTDE', 'UNITARIO', 'CAIXA', 'VLRSUBST', 'ALIQIPI', 'VLRIPI', 'CST', 'CODCFOP', 'VLRICMS', 'BCALCICMS', 'BCALCSUBST', 'ALIQPIS', 'ALIQCOFINS', 'VLRPIS', 'VLRCOFINS', 'ALIQICMS', 'CODCST', 'IPI', 'CODCSOSN', 'BASEPIS', 'BASECOFINS', 'ALIQST', 'TOTPRODFRETE', 'VLRFRETE', 'BASEIPI', 'DESCSUFRAMA', 'DESCORGPUBLICO', 'ICMSDESONERACAO', 'CSTPIS', 'CSTCOFINS', 'UNITARIOSUBST', 'CODCALC', 'CSTIPI', 'UNITARIOIPI', 'VTOTTRIB', 'PREDBC', 'PREDBCST', 'VLRICMSDESON'];

	protected $table = 'EXPEDICAOITENS';

	protected $primaryKey = 'CODEXP';

}
