<?php

namespace App\Entities;

class Expedicoesexcluida extends FirebirdModel
{

	protected $fillable = ['AUXEXPEDICOESEXCLUIDAS', 'OBS', 'PESOLIQUIDO', 'DATA', 'DATAALT', 'DATACRIA', 'DATAEXCLUI', 'PESOBRUTO', 'SEPARADOR', 'CODEXP', 'CODUSUALT', 'CODUSUCRIA', 'CODUSUEXCLUI', 'VOLUME', 'DTENTREGA', 'NUMEXP', 'EMBALADOR', 'CODCLI', 'CODLOJA', 'CONFERENTE', 'PREVENTREGA', 'MOTIVOEXCLUSAO', 'ISULTIMA'];

	protected $table = 'EXPEDICOESEXCLUIDAS';

}
