<?php

namespace App\Entities;

class Fornecedor extends FirebirdModel
{

	protected $fillable = ['AUXFORNECEDORES', 'OBS', 'DATACAD', 'CODUSUALT', 'CODUSUCRIA', 'FISJUR', 'DATAALT', 'DATACRIA', 'UF', 'CEP', 'CIDADE', 'BAIRRO', 'FANTASIA', 'SITE', 'RGIE', 'RAZAO', 'EMAIL', 'ENDERECO', 'FAX1', 'FAX2', 'FONE1', 'FONE2', 'CONTATO1', 'CONTATO2', 'CPCN', 'ICMSFRETE', 'CADINATIVO', 'CODPAIS', 'CODIMPORT', 'EXPORTASPED', 'CODCAMPOIMPXML', 'CAMPOIMPXML', 'CREDITAICMS', 'CODNFOPERACAO', 'IDESTRANGEIRO', 'CODNFIEDEST'];

	protected $table = 'FORNECEDORES';

	protected $primaryKey = 'CODFOR';

}
