<?php

namespace App\Entities;

class Nfcfopprod extends FirebirdModel
{

	protected $fillable = ['AUXNFCFOPPROD', 'CODUSU', 'CODCFOPC', 'CODCFOPV', 'CODCFOPDC', 'CODCFOPDV', 'CODUSUALT', 'CODCFOPBON', 'CODCFOPTRA', 'CODUSUCRIA', 'CODCFOPCFORA', 'CODCFOPVFORA', 'CODCFOPDCFORA', 'CODCFOPDVFORA', 'CODCFOPBONFORA', 'CODCFOPTRAFORA', 'DATAALT', 'DATACRIA', 'DESCRICAO', 'USACFOPTIPOSAI', 'USACFOPTIPOENT', 'CODCFOPISENTO', 'CODCFOPISENTOF'];

	protected $table = 'NFCFOPPROD';

	protected $primaryKey = 'CODCFOPPROD';

}
