<?php

namespace App\Entities;

class Nfservico extends FirebirdModel
{

	protected $fillable = ['NUMNFSERV', 'NUMNFRPS', 'AUXNOTAFISCAL', 'CODOS', 'CODOSAUX', 'OS', 'VALTOTALNOTA', 'TOTALSERV', 'OUTRASDESPESAS', 'DEDUCOES', 'DESCONTOOS', 'HORASAIDA', 'DTEMISSAO', 'CODLOJA', 'SERIE', 'DADOSADIC', 'RAZAO', 'ENDERECO', 'CODCID', 'CIDADE', 'BAIRRO', 'FONE1', 'CPCN', 'CODPAIS', 'UF', 'CEP', 'ENDNUM', 'EMAIL', 'RAZAOINT', 'IMUNICINT', 'CPCNINT', 'ISRETIDO', 'VLRISSRETIDO', 'VLRPIS', 'ALIQPIS', 'VLRCOFINS', 'ALIQCOFINS', 'VLRINSS', 'ALIQINSS', 'VLRIR', 'ALIQIR', 'VLRCSLL', 'ALIQCSLL', 'BASECALCISS', 'VLRISS', 'ALIQISS', 'CANCELADA', 'DTCANCELAMENTO', 'CODUSUEMITE', 'CODUSUCANCELA', 'PROTOCOLONFSE', 'CODMSGNFE', 'MSGERRONFE', 'STATUSENVIO', 'TIPOTRIBNFSE', 'INSCRICAOMUNICIPAL', 'CODIGOOBRA', 'CODIGOART', 'ENDERECOTIPO', 'ENDERECOCOMPL', 'CODCIDPRESTACAO', 'DESCONTOINCONDICIONADO', 'DESCONTOCONDICIONADO'];

	protected $table = 'NFSERVICOS';

	protected $primaryKey = 'CODNFS';

}
