<?php

namespace App\Entities;

class Notafiscal extends FirebirdModel
{

	protected $fillable = ['AUXNOTAFISCAL', 'CLFISC', 'CIDADE', 'BAIRRO', 'BASECALCICMS', 'BASECALCICMSSUBS', 'OBS', 'UNID', 'QTDE', 'QTDESER', 'CODPRODS', 'UNITARIO', 'TOTALPROD', 'TOTALSERV', 'DESCPRODS', 'DESCSERVS', 'CFOPPRODS', 'CFOPSERVS', 'ICMSPRODS', 'SITTRIBUT', 'ISENTOSERVS', 'ISENTOPRODS', 'UNITARIOSER', 'NINCIDEPRODS', 'NINCIDESERVS', 'CODOS', 'NUMNOTA', 'CODTRANSP', 'TRANSCIDADE', 'TRANSENDERECO', 'OS', 'TOTAL', 'VALISS', 'ISENTO', 'VALFRETE', 'VALORICMS', 'VALSEGURO', 'VALTOTALNOTA', 'VALORICMSSUBS', 'TOTALGERALSERV', 'OUTRASDESPESAS', 'TOTALGERALPRODS', 'DESPESASACESSORIAS', 'HORASAIDA', 'DATAOS', 'DTSAIDA', 'DATAOSFIN', 'DTEMISSAO', 'CODEXP', 'CODENT', 'CODTRA', 'CODVEI', 'CODLOJA', 'ENTSAI', 'ANULADA', 'ISSUBST', 'ISRETIDO', 'BONIFICA', 'ISISENTO', 'CANCELADA', 'IMPRIMINDO', 'ISCFOPISENTO', 'ISELETRONICA', 'ENVIADOSINTEGRA', 'PSAI', 'PENT', 'PFRDEST', 'PFREMIT', 'EMITENTE', 'SITUACAONOTA', 'UF', 'MODELO', 'TRANSUF', 'SUBSERIE', 'SERIE', 'CFOP1', 'CFOP2', 'CFOP3', 'CEP', 'CFOP4', 'VEIANO', 'VEIMOTOR', 'CFOP', 'NPEDIDO', 'SPEDIDO', 'TRAQTDE', 'VENDEDOR', 'TRAMARCA', 'VEIPLACA', 'TRANSCPCN', 'TRANSRGIE', 'TRANUMERO', 'TRAESPECIE', 'TRAPESOLIQ', 'CODSITTRIB', 'TRAPESOBRUTO', 'VEIMODELO', 'CPCNVENDEDOR', 'NATUREZAOP', 'TRANSPORTADORA', 'RAZAO', 'ENDCOB', 'ENDERECO', 'LOCALENTREGA', 'VEICOR', 'RGIE', 'FONE1', 'NATOP1', 'NATOP2', 'NATOP3', 'NATOP4', 'VEICHASSI', 'FONEVENDEDOR', 'CPCN', 'MSGCANCELA', 'CONDPAG', 'MSGSUBST', 'MSGRETENCAO', 'PRAZOPAG', 'DADOSADIC2', 'DESCONTOOS', 'VALTOTALIPI', 'NUMENT', 'NUMTRANSF', 'VEIHODOMETRO', 'POSSUIENTREGA', 'CODPAIS', 'CODDEVOLUCAO', 'ISNOTBOANFP', 'DTCANCELAMENTO', 'CODOSAUX', 'INFOFINAN', 'ISNOTBOASINTEGRA', 'BCALCMSG', 'ICMMSG', 'SEPARADOR', 'EMBALADOR', 'CONFERENTE', 'CODUSUEMITE', 'CODUSUCANCELA', 'ISSIMPFATURA', 'CHAVENFE', 'PROTOCOLONFE', 'NSUFRAMA', 'ISSUFRAMA', 'VLRPIS', 'ALIQPIS', 'VLRCOFINS', 'ALIQCOFINS', 'CODCID', 'CODOSAUX2', 'OSAUX', 'CODLANCAUX', 'MSGCREDPRENF', 'MSGDEPOSITONF', 'ENDNUM', 'MSGERRONFE', 'ALIQDESCONTOSUFRAMA', 'REGISTRADANFP', 'CRT', 'EMAIL', 'MODFRETE', 'CODMSGNFE', 'INUTILIZADA', 'ISDENEGADA', 'RECIBONFE', 'COMPLEMENTO', 'TRAVSERV', 'TRAVBCRET', 'TRAICMSRET', 'TRAVLRICMS', 'TRACFOP', 'TRACMUNFG', 'TRAPLACA', 'TRAVEIUF', 'TRARNTC', 'INDPAG', 'NSEQCANC', 'VTOTTRIB', 'NAOENVIAFATURA', 'IMUNICIPAL', 'CHAVEREFERENCIADA', 'CODNFOPERACAO', 'INDFINAL', 'IDESTRANGEIRO', 'VLRICMSDESON', 'CODNFIEDEST', 'CODNFTIPOEMISSAO', 'VLRII', 'VLRDESCONTO'];

	protected $table = 'NOTAFISCAL';

	protected $primaryKey = 'CODNF';

}
