<?php

namespace App\Entities;

class OsItemPro extends FirebirdModel
{

	protected $fillable = ['AUXOSITENSPRO', 'NUMITEM', 'REVHISTORICO', 'REVENVMENSCEL', 'IMPRESSO', 'ENTREGUE', 'ENVIADOAOFRN', 'REVRESOLVIDO', 'ORDEM', 'CODOS', 'CODPRO', 'CODTEC', 'CODVND', 'CODLOJAI', 'CODOSORC', 'NUMITEMORC', 'CODLOJASAII', 'CODSTATUSITEM', 'TIPOI', 'GARANTIA', 'NOTISMOV', 'CONFLOGISTICA', 'LOGISTICARESOLV', 'OBS', 'COMISSAO', 'QTDE', 'CUSTO', 'UNITARIO', 'IPI', 'DESCONTO', 'DESCONTOPCT', 'PCTDESCDILUIDO', 'NAOALTERAESTOQUE', 'CODENTDEV', 'PRAZOENT', 'VLRSUBST', 'VLRFRETE', 'QTDEEFETIVADA', 'PRECOBASE', 'UNITCOMDESC', 'UNITCDESCSEMIPI', 'TOTALPRD', 'UNITCOMDESCDILUIDO', 'TOTALCOMDESC', 'QTDEEXP', 'QTDEEXPFALTA', 'CST', 'CODCFOP', 'VLRICMS', 'ALIQICMS', 'BCALCICMS', 'BCALCSUBST', 'VLRIPI', 'ALIQIPI', 'CODCST', 'ALIQCOFINS', 'VLRPIS', 'VLRCOFINS', 'ALIQPIS', 'CODCSOSN', 'ALIQST', 'BASEPIS', 'BASECOFINS', 'TOTPRODFRETE', 'BASEIPI', 'DESCSUFRAMA', 'DESCORGPUBLICO', 'ICMSDESONERACAO', 'CSTPIS', 'CSTCOFINS', 'UNITARIOSUBST', 'CODCALC', 'CSTIPI', 'UNITARIOIPI', 'TINHANF', 'VTOTTRIB', 'TOTIMPOSTOSIMPLES', 'QTDECONFERIDA', 'PREDBC', 'PREDBCST', 'VLRICMSDESON', 'EXNDRAW', 'EXNRE', 'EXCHNFE', 'EXQEXPORT', 'NUMPEDCOMP', 'ORDEMPEDCOMP', 'OUTRASDESP', 'VLRICMSOP', 'PCTDIFERIMENTO', 'VLRICMSDIFERIDO', 'DESCONTONF'];

	protected $table = 'OSITENSPRO';

}
