<?php

namespace App\Entities;

class Ositensser extends FirebirdModel
{

	protected $fillable = ['AUXOSITENSSER', 'NUMITEM', 'OBSLONGA', 'REVHISTORICO', 'REVENVMENSCEL', 'REVRESOLVIDO', 'ORDEM', 'CODSER', 'CODTEC', 'CODVND', 'CODOSORC', 'NUMITEMORC', 'GARANTIA', 'COMISSAO', 'QTDE', 'CUSTO', 'UNITARIO', 'DESCONTO', 'DESCONTOPCT', 'PCTDESCDILUIDO', 'ISCOMIESP', 'TEMPOGASTO', 'AUXCODOSSER', 'PRECOBASE', 'UNITCOMDESC', 'TOTALSRV', 'UNITCOMDESCDILUIDO', 'TOTALCOMDESC', 'BASECALCISS', 'VLRISS', 'ALIQISS', 'VLRPISNFSE', 'VLRCOFINSNFSE', 'VLRCSLLNFSE', 'VLRINSSNFSE', 'VLRIRNFSE'];

	protected $table = 'OSITENSSER';

	protected $primaryKey = 'CODOS';

}
