<?php

namespace App\Entities;

class Parcela extends FirebirdModel
{

	protected $fillable = ['AUXPARCELAS', 'NUMPAR', 'DTEMI', 'DTPAGTO', 'ANTDTEMI', 'DTVENCTO', 'PAGO', 'TAXA', 'ADIC', 'VALOR', 'JUROS', 'MULTA', 'VALORPG', 'CODBAN', 'CODUSU', 'CODTIPO', 'ANTCODUSU', 'CODUSUALT', 'ANTCODTIPO', 'CCDIG', 'AGDIG', 'CHEQUEDIG', 'FECHADA', 'BANCO', 'NOSSONUMERO', 'NOME', 'AG', 'CC', 'NUMDOC', 'TIPODOC', 'CPFCNPJ', 'OBS', 'OBSCNAB', 'CODPARSTAT', 'CODUSUCRIA', 'NUMDOCBOLETO', 'DATAOCORRENCIA', 'DUPLLETRA', 'CLICONTRATO', 'CODENTDEV', 'DTEMAILDADOSFATURAMENTO', 'DTVENCTOORIGINAL', 'CANCELADO', 'CANCELADOOBS', 'DIASATRASO', 'CODCON', 'CODPAR', 'CODPAGAM', 'CODPARORI', 'CODUSUCANC', 'DTCANCELADO', 'CODSUBCON', 'AUXTEMPO', 'VALORABATIMENTO', 'VALOROUTROSCREDITOS', 'PCTTAXA', 'PCTMULTA', 'PCTJUROS', 'ANTHORAEMI', 'VALORIOF', 'VALORDESCONTO', 'AUXVALORABATIMENTO', 'HORAEMI', 'CODPORTADOR', 'CODPARINICIAL', 'CODBORDEROITENS', 'NUMBORDERO', 'ISUSOUCREDITO', 'DTHORAEMIREL', 'DTBOLETOENVCNAB', 'DTBOLETOIMPRESSO', 'CODFINREC', 'DTCOMPETENCIA', 'DATACRIA', 'CODCOBRANCA'];

	protected $table = 'PARCELAS';

	protected $primaryKey = 'CODFIN';

}
