<?php

namespace App\Entities;

class Pedidoscompiten extends FirebirdModel
{

	protected $fillable = ['AUXPEDIDOSCOMPITENS', 'NUMITEM', 'OBS', 'CODPRO', 'CODLOJAI', 'CREDITAICMS', 'AJUSTAVALORES', 'GARI', 'VLRICMS', 'ALIQSUBST', 'PRECOTABELA', 'DESCPRECTAB', 'VLRICMSSUBST', 'RATFRTSEGDESPICMS', 'SEGURO', 'FRETEVLR', 'OUTRASDESPESAS', 'ICMS', 'UNITARIO', 'IPI', 'QTDE', 'QTDENAOENTR', 'UNITARIOSEMIPI', 'TOTALPRD', 'PRECOTABELACOMDESC', 'ALIQINTICMSLOJA'];

	protected $table = 'PEDIDOSCOMPITENS';

	protected $primaryKey = 'CODPEDCOMP';

}
