<?php

namespace App\Entities;

class Produto extends FirebirdModel
{

	protected $fillable = ['AUXPRODUTOS', 'DESCRICAODET', 'SITE', 'IPIVND', 'DA_DESC', 'DESTAQUE', 'CODFOR', 'CODGRU', 'CODMAR', 'QTDMIN', 'TROCAKM', 'TROCAMES',
	'CODIGONUM', 'CODSUBGRU', 'CODUSUALT', 'CODUSUCRIA', 'USADO', 'ATIVO',
	'DATAALT', 'DATACRIA', 'UN', 'CODALIQ', 'VALORALIQ', 'CST', 'CODIGO',
	'CODIGOAUX', 'LOCALIZACAO', 'DESCRICAOSITE', 'CF', 'FOTOPQ', 'FOTOGR',
	'DESCRICAO', 'APLICACAO', 'FATOR', 'PREMARK1', 'PREMARK2', 'PREMARK3',
	'VLRMOEDA', 'PCTMARK1', 'PCTMARK2', 'PCTMARK3', 'PCTMARK4', 'OBS2',
	'ULTALTVALORES', 'CODCFOPPROD', 'DESTAQUEORDEM', 'ISKIT', 'CONSUMO',
	'PROMOCAO', 'APENASMP', 'CREDITAICMS', 'ISIMPORTADO', 'FOTOPQNOME',
	'FOTOGRNOME', 'OBS', 'PREMARK4', 'PREMARK5', 'POSMARK1', 'POSMARK2',
	'PRECOTABELA', 'COMISSAOVLR', 'PREMARKMIN1', 'PREMARKMIN2', 'PREMARKMIN3',
	'PREMARKMIN4', 'PREMARKMIN5', 'ISPROMOCIONAL', 'CUSTOBASE', 'IPI', 'ICMS',
	'CUSTO', 'PRECO3', 'PRECO4', 'PRECO5', 'MARGEM', 'CUSTO2', 'MARGEM3',
	'MARGEM4', 'MARGEM5', 'COD_MDA', 'COMISSAO', 'PRECOMIN3', 'PRECOMIN4',
	'PRECOMIN5', 'MARGEMMIN', 'PRECOVENDA', 'MARGEMMIN3', 'MARGEMMIN4',
	'MARGEMMIN5', 'MARGEMATAC', 'ALIQ_SUBST', 'PREVCOMPRA', 'PRECOMINIMO',
	'QTDEPARAVND', 'QTDEESTOQUE', 'COMISSAOTEC', 'PREVMONTAGEM',
	'MARGEMMINATAC', 'COMISSAOPROMO', 'PRECOVENDAATAC', 'PRECOMINIMOATAC',
	'ICMSPRODSINTEGRA', 'CODAUXBASE', 'COMPLEMENTOUNIDADE', 'PESOLIQ',
	'PESOBRUTO', 'CADINATIVO', 'TRIBUTAIPI', 'CAIXAMASTER', 'QTDEINNER',
	'CUBAGEM', 'NCM', 'NFDESCRI', 'CODBARRAS', 'ISGENERICO', 'TENSAO', 'MINMAX',
	'NOMINAL', 'A', 'POTENCIA', 'FREQUENCIA', 'CLASSE2', 'GRADUDEPROTECAO',
	'DUN14', 'ISLOTE', 'PIS', 'COFINS', 'ISPNEU', 'ISDERIVPETROLEO',
	'EMBALAGEM', 'ISARTCIRURGICO', 'ISMETAL', 'ISCREDPREZUMIDO', 'PREDBC',
	'PREDBCST', 'CODNCM', 'ORIGEM', 'ISREDUCAOICMS', 'ISISENTOICMS', 'CSTIPI',
	'CODIMPORT', 'ALIQCF', 'CODIGOANP', 'CODTIPOPRODUTO', 'CODUN',
	'CODPRODORIGEM', 'PESO', 'PCTMIXGN'];

	protected $table = 'PRODUTOS';

	protected $primaryKey = 'CODPRO';

	public $selectable = ['CODPRO', 'DESCRICAO'];
}
