<?php

namespace App\Entities;

class Workflow extends FirebirdModel
{

	protected $fillable = ['AUXWORKFLOW', 'CODWORK', 'TITMENSAGEM', 'CODBANCO', 'DATAALT', 'DATACRIA', 'DATALIMITE', 'TEXTOMENSAGEM', 'TIPO', 'TITULO', 'INATIVO', 'CODUSUALT', 'CODUSUCRIA', 'CODGRURECEBE', 'CODUSURECEBE', 'COMANDO', 'SAB', 'SEG', 'SEX', 'TER', 'DOM', 'QUA', 'QUI', 'ISOCULTO', 'CODIGO', 'TIPOCMD', 'TIPODEST', 'DESTINATARIOTXT', 'CMDDEST', 'DIAMES', 'HORA', 'VEZES', 'CMDAUXILIAR'];

	protected $table = 'WORKFLOW';

}
